const segments = [
  {
    id: 1, from: "Start", to: "Bridal Veil #1", miS: 0, miE: 5, dist: 5,
    clockS: "Sat 6:00am", clockE: "Sat 7:58am", time: "1h58m", hours: 1.97, avgPace: "23:38", avgMph: "2.5", avgGrade: "7.6", maxClimb: "+16.2", maxDescent: "0.0", gradeShift: null, segGain: 2401, segLoss: 0, netFt: "+2,051", netDir: "climb",
    elevS: 8750, elevE: 10801, conditions: "Cool morning, 45-55°F, climbing toward Wasatch area",
    tailwind: 130, waterMl: 720, gels: 2, electrolyte: "Salt tabs", saltTabs: 11, lmntPackets: 0,
    pickup: [], dropoff: [], socks: "Start fresh",
    bladder: "Fill bladder full before start — required every segment, not just long ones", color: "#E8943A",
    note: "Fresh legs, cool temps — settle into pace, don't go out too hot on the early climb.",
  },
  {
    id: 2, from: "Bridal Veil #1", to: "Tomboy", miS: 5, miE: 10, dist: 5,
    clockS: "Sat 7:58am", clockE: "Sat 10:13am", time: "2h15m", hours: 2.25, avgPace: "27:00", avgMph: "2.2", avgGrade: "16.6", maxClimb: "+19.6", maxDescent: "-20.2", gradeShift: "Mi 8.0: +16% climb → -8% descent", segGain: 3182, segLoss: 1985, netFt: "+1,023", netDir: "climb",
    elevS: 10801, elevE: 11824, conditions: "Warming, 50-60°F, sustained altitude 11-13.5K via Telluride Peak",
    tailwind: 148, waterMl: 820, gels: 2, electrolyte: "Salt tabs", saltTabs: 12, lmntPackets: 0,
    pickup: ["Refill water (no drop bag here)"], dropoff: [], socks: "No change",
    bladder: "Refill bladder fully — single mix for entire next segment", color: "#E8943A",
    note: "Crosses Telluride Peak (13,500ft) — your highest point on course, first of three 13K+ crossings.",
  },
  {
    id: 3, from: "Tomboy", to: "Oak St (Drop Bag #1)", miS: 10, miE: 17, dist: 7,
    clockS: "Sat 10:13am", clockE: "Sat 12:44pm", time: "2h31m", hours: 2.52, avgPace: "21:36", avgMph: "2.8", avgGrade: "13.9", maxClimb: "+21.0", maxDescent: "-27.8", gradeShift: "Mi 13.0: steep descent begins (-27.8%)", segGain: 1323, segLoss: 4759, netFt: "-2,896", netDir: "descent",
    elevS: 11824, elevE: 8928, conditions: "Midday, 60-65°F (warmest of the day), steep Imogene descent",
    tailwind: 164, waterMl: 910, gels: 3, electrolyte: "LMNT", saltTabs: 0, lmntPackets: 1.3,
    pickup: [], dropoff: [], socks: "No change", bladder: "Refill bladder fully — single mix for entire next segment",
    color: "#E8943A",
    note: "Steepest descent on the course (-27.8%) happens in this segment. Quads will feel this.",
  },
  {
    id: 4, from: "Oak St (DB1)", to: "Prospect", miS: 17, miE: 20, dist: 3,
    clockS: "Sat 12:44pm", clockE: "Sat 2:35pm", time: "1h50m", hours: 1.83, avgPace: "36:36", avgMph: "1.6", avgGrade: "18.3", maxClimb: "+22.8", maxDescent: "+15.2", gradeShift: null, segGain: 3424, segLoss: 0, netFt: "+2,905", netDir: "climb",
    elevS: 8928, elevE: 11833, conditions: "Warmest part of day, 60-65°F, Ajax Peak climb begins",
    tailwind: 119, waterMl: 660, gels: 2, electrolyte: "LMNT", saltTabs: 0, lmntPackets: 0.9,
    pickup: ["DROP BAG #1: fresh socks", "Foot lube/blister kit", "Sunscreen reapply", "Spare pole tips", "6-8 SIS gels resupply", "Tailwind resupply", "LMNT resupply (primary for next 2 segments)", "Salt tabs (backup, just in case)"],
    dropoff: ["DROP BAG #1 left here (picked up post-race)"],
    socks: "Change to fresh pair", bladder: "Refill + check fit",
    color: "#A78BFA",
    note: "Drop Bag #1. Quick stop — 5-8 min. Eat real food from aid station too if available.",
  },
  {
    id: 5, from: "Prospect", to: "Gold Hill", miS: 20, miE: 24, dist: 4,
    clockS: "Sat 2:35pm", clockE: "Sat 4:12pm", time: "1h36m", hours: 1.60, avgPace: "24:00", avgMph: "2.5", avgGrade: "11.4", maxClimb: "+23.7", maxDescent: "-22.2", gradeShift: "Mi 22.5: +23.7% peak then sharp drop", segGain: 1781, segLoss: 1074, netFt: "+604", netDir: "climb",
    elevS: 11833, elevE: 12437, conditions: "Afternoon, 55-62°F, ridgeline exposure — Mile and a Half of Sky",
    tailwind: 103, waterMl: 570, gels: 2, electrolyte: "LMNT", saltTabs: 0, lmntPackets: 0.8,
    pickup: [], dropoff: [], socks: "No change", bladder: "Refill bladder fully — single mix for entire next segment",
    color: "#E8943A",
    note: "Exposed ridgeline section. Watch weather — afternoon is when storms are most likely to build.",
  },
  {
    id: 6, from: "Gold Hill", to: "Bridal Veil (Drop Bag #2)", miS: 24, miE: 35, dist: 11,
    clockS: "Sat 4:12pm", clockE: "Sat 7:54pm", time: "3h42m", hours: 3.70, avgPace: "20:11", avgMph: "3.0", avgGrade: "10.9", maxClimb: "+21.4", maxDescent: "-14.8", gradeShift: "Mi 25.0: +18.9% climb → -10.7% descent", segGain: 2851, segLoss: 4618, netFt: "-1,480", netDir: "descent",
    elevS: 12437, elevE: 10957, conditions: "Late afternoon into evening, cooling 45-58°F, Black Bear + Brooklyn Pass",
    tailwind: 233, waterMl: 1295, gels: 4, electrolyte: "Salt tabs", saltTabs: 20, lmntPackets: 0,
    pickup: [
      "DROP BAG #2: full headlamp + battery swap", "Warm layer / gloves / hat",
      "2nd fresh socks", "Pole re-grip check", "Fresh base layer", "Anti-chafe reapply",
      "8-10 SIS gels resupply", "Tailwind resupply", "Pickles, caffeine gels x3-4",
      "Salt tabs resupply (primary from here)", "LMNT (backup, just in case)",
    ],
    dropoff: ["DROP BAG #2 left here (picked up post-race)"],
    socks: "Change to fresh pair", bladder: "Refill bladder — last fill before overnight stretch",
    color: "#A78BFA", pacer: true,
    note: "Most important stop of the race. Pacer joins here. Take 10-15 min. Sun sets ~8:15pm — headlamp goes on soon after this stop.",
  },
  {
    id: 7, from: "Bridal Veil (DB2)", to: "Red Mtn", miS: 35, miE: 42, dist: 7,
    clockS: "Sat 7:54pm", clockE: "Sat 10:20pm", time: "2h26m", hours: 2.43, avgPace: "20:50", avgMph: "2.9", avgGrade: "9.6", maxClimb: "+18.8", maxDescent: "-15.2", gradeShift: null, segGain: 2282, segLoss: 1916, netFt: "+318", netDir: "climb",
    elevS: 10957, elevE: 11275, conditions: "Dusk into dark, 40-50°F dropping, headlamp required by end of segment",
    tailwind: 152, waterMl: 845, gels: 2, electrolyte: "Salt tabs", saltTabs: 13, lmntPackets: 0,
    pickup: [], dropoff: [], socks: "No change", bladder: "Refill bladder fully — single mix for entire next segment",
    color: "#4A9FE8",
    note: "First fully dark segment. Pacer's job shifts to scanning trail with their own light. Crew access here (vehicle).",
  },
  {
    id: 8, from: "Red Mtn", to: "Burro Bridge", miS: 42, miE: 50, dist: 8,
    clockS: "Sat 10:20pm", clockE: "Sun 12:49am", time: "2h28m", hours: 2.47, avgPace: "18:32", avgMph: "3.2", avgGrade: "7.8", maxClimb: "+11.1", maxDescent: "-16.7", gradeShift: null, segGain: 1353, segLoss: 2555, netFt: "-1,009", netDir: "descent",
    elevS: 11275, elevE: 10266, conditions: "Full night, 35-42°F, net descent through Howard Fork drainage",
    tailwind: 152, waterMl: 845, gels: 2, electrolyte: "Salt tabs", saltTabs: 14, lmntPackets: 0,
    pickup: [], dropoff: [], socks: "No change", bladder: "Refill bladder fully — single mix for entire next segment",
    color: "#4A9FE8",
    note: "Coldest stretch begins. Crew access here (vehicle) — good spot for a warm layer check with pacer.",
  },
  {
    id: 9, from: "Burro Bridge", to: "Ophir (Drop Bag #3)", miS: 50, miE: 56, dist: 6,
    clockS: "Sun 12:49am", clockE: "Sun 3:26am", time: "2h36m", hours: 2.60, avgPace: "26:00", avgMph: "2.3", avgGrade: "12.6", maxClimb: "+24.8", maxDescent: "-15.6", gradeShift: "Mi 55.0: steepest climb on course (+24.8%)", segGain: 3314, segLoss: 1383, netFt: "+1,643", netDir: "climb",
    elevS: 10266, elevE: 11909, conditions: "Deep overnight, 33-40°F (coldest of race), Ophir Pass climb",
    tailwind: 158, waterMl: 880, gels: 3, electrolyte: "Salt tabs", saltTabs: 14, lmntPackets: 0,
    pickup: [
      "DROP BAG #3: fresh headlamp batteries (last chance)", "Dry socks (optional morale)",
      "Light gloves if not already carrying", "3-4 SIS gels resupply", "Tailwind resupply", "Caffeine gel x1-2",
      "Salt tabs resupply", "LMNT (backup, just in case)",
    ],
    dropoff: ["DROP BAG #3 left here (picked up post-race)"],
    socks: "Optional 3rd change for morale", bladder: "Final refill of the race",
    color: "#A78BFA",
    note: "Mile 56 is the classic DNF trap — 9 miles feels far at 3am after 21+ hours. Don't linger. Pacer keeps you moving.",
  },
  {
    id: 10, from: "Ophir (DB3)", to: "Finish", miS: 56, miE: 63, dist: 7,
    clockS: "Sun 3:26am", clockE: "Sun 5:59am", time: "2h33m", hours: 2.55, avgPace: "21:51", avgMph: "2.7", avgGrade: "14.7", maxClimb: "+23.1", maxDescent: "-21.5", gradeShift: "Mi 57.0: summit then steep drop (-21.5%)", segGain: 1409, segLoss: 5029, netFt: "-3,159", netDir: "descent",
    elevS: 11909, elevE: 8750, conditions: "Pre-dawn into sunrise (~6:30am), 33-45°F warming, Oscar's Pass then final descent",
    tailwind: 153, waterMl: 850, gels: 2, electrolyte: "Salt tabs", saltTabs: 14, lmntPackets: 0,
    pickup: [], dropoff: [], socks: "No change", bladder: "Use remaining — no more refills",
    color: "#3CB897",
    note: "Final climb to Oscar's Pass (13,104ft, steepest climb on course at +24.8%) then descent to finish. Sunrise arrives as you descend Bear Creek.",
  },
];

