const segments = [
  {
    id: 1, from: "Start", to: "Bridal Veil #1", miS: 0, miE: 4, dist: 4, distReal: 4.52,
    clockS: "Sat 6:00am", clockE: "Sat 8:01am", time: "2h01m", hours: 2.02, avgPace: "26:49", avgMph: "2.2",
    avgGrade: "6.5", maxClimb: "+11.3", maxDescent: "-0.6",
    segGain: 1982, segLoss: 0, netFt: "+1,556", netDir: "climb",
    elevS: 8763, elevE: 10319, conditions: "Cool morning, 45-55°F, climbing toward Wasatch area",
    tailwind: 80, waterMl: 997, dilutedMl: 997, plainMl: 0, tailwindConc: 0.08,
    gels: 4, gelsPerHr: 2, carbTargetHr: 80, actualCarbHr: 80.0,
    saltCaps: 2, saltCapType: "original", sodiumHr: 668,
    caffeineHr: 0,
    cutoffClock: "7:30am", cutoffHours: 1.5, modeledArrivalHours: 2.02, cutoffMarginHours: -0.52,
    amenities: {"water": true, "food": false, "dropBag": false, "crew": false, "note": "Water only"},
    pickup: [],
    dropoff: [],
    socks: "Start fresh", bladder: "Fill bladder full before start — required every segment, not just long ones",
    color: "#E8943A",
    note: "Fresh legs, cool temps — settle into pace, don't go out too hot on the early climb.",
  },
  {
    id: 2, from: "Bridal Veil #1", to: "Tomboy", miS: 4, miE: 10, dist: 6, distReal: 6.17,
    clockS: "Sat 8:01am", clockE: "Sat 10:37am", time: "2h35m", hours: 2.59, avgPace: "25:11", avgMph: "2.4",
    avgGrade: "3.7", maxClimb: "+30.4", maxDescent: "-31.3",
    segGain: 3738, segLoss: 2493, netFt: "+1,193", netDir: "climb",
    elevS: 10319, elevE: 11512, conditions: "Warming, 50-60°F, sustained altitude 11-13.5K via Telluride Peak",
    tailwind: 33, waterMl: 1345, dilutedMl: 494, plainMl: 851, tailwindConc: 0.0675,
    gels: 8, gelsPerHr: 3, carbTargetHr: 80, actualCarbHr: 80.0,
    saltCaps: 6, saltCapType: "original", sodiumHr: 686,
    caffeineHr: 0,
    cutoffClock: "11:00am", cutoffHours: 5, modeledArrivalHours: 4.61, cutoffMarginHours: 0.39,
    amenities: {"water": true, "food": true, "dropBag": false, "crew": false},
    pickup: ["Refill water (no drop bag here)"],
    dropoff: [],
    socks: "No change", bladder: "Refill bladder fully — single mix for entire next segment",
    color: "#E8943A",
    note: "Crosses Telluride Peak (13,500ft) — your highest point on course, first of three 13K+ crossings.",
  },
  {
    id: 3, from: "Tomboy", to: "Oak St (Drop Bag #1)", miS: 10, miE: 17, dist: 7, distReal: 6.47,
    clockS: "Sat 10:37am", clockE: "Sat 12:31pm", time: "1h54m", hours: 1.9, avgPace: "17:37", avgMph: "3.4",
    avgGrade: "-8.1", maxClimb: "+37.0", maxDescent: "-37.1",
    segGain: 1362, segLoss: 4277, netFt: "-2,762", netDir: "descent",
    elevS: 11512, elevE: 8751, conditions: "Midday, 60-65°F (warmest of the day), steep Imogene descent",
    tailwind: 69, waterMl: 1235, dilutedMl: 1024, plainMl: 211, tailwindConc: 0.0675,
    gels: 4, gelsPerHr: 2, carbTargetHr: 80, actualCarbHr: 80.0,
    saltCaps: 3, saltCapType: "original", sodiumHr: 740,
    caffeineHr: 0,
    cutoffClock: "2:00pm", cutoffHours: 8, modeledArrivalHours: 6.51, cutoffMarginHours: 1.49,
    amenities: {"water": true, "food": true, "dropBag": true, "crew": true, "note": "Vehicle access"},
    pickup: [],
    dropoff: [],
    socks: "No change", bladder: "Refill bladder fully — single mix for entire next segment",
    color: "#E8943A",
    note: "Steepest descent on the course (-27.8%) happens in this segment. Quads will feel this.",
  },
  {
    id: 4, from: "Oak St (Drop Bag #1)", to: "Prospect", miS: 17, miE: 22, dist: 5, distReal: 5.06,
    clockS: "Sat 12:31pm", clockE: "Sat 3:01pm", time: "2h31m", hours: 2.51, avgPace: "29:46", avgMph: "2.0",
    avgGrade: "9.0", maxClimb: "+34.3", maxDescent: "-34.9",
    segGain: 3465, segLoss: 950, netFt: "+2,411", netDir: "climb",
    elevS: 8751, elevE: 11161, conditions: "Warmest part of day, 60-65°F, Ajax Peak climb begins",
    tailwind: 27, waterMl: 1634, dilutedMl: 401, plainMl: 1233, tailwindConc: 0.0675,
    gels: 8, gelsPerHr: 3, carbTargetHr: 80, actualCarbHr: 80.0,
    saltCaps: 6, saltCapType: "original", sodiumHr: 661,
    caffeineHr: 0,
    cutoffClock: "5:00pm", cutoffHours: 11, modeledArrivalHours: 9.02, cutoffMarginHours: 1.98,
    amenities: {"water": true, "food": true, "dropBag": false, "crew": false},
    pickup: ["DROP BAG #1: fresh socks", "Foot lube/blister kit", "Sunscreen reapply", "Spare pole tips", "6-8 SIS gels resupply", "Tailwind resupply", "SaltStick capsules resupply"],
    dropoff: ["DROP BAG #1 left here (picked up post-race)"],
    socks: "Change to fresh pair", bladder: "Refill + check fit",
    color: "#E8943A",
    note: "Drop Bag #1. Quick stop — 5-8 min. Eat real food from aid station too if available.",
  },
  {
    id: 5, from: "Prospect", to: "Gold Hill", miS: 22, miE: 26.5, dist: 4.5, distReal: 4.21,
    clockS: "Sat 3:01pm", clockE: "Sat 4:54pm", time: "1h53m", hours: 1.88, avgPace: "26:48", avgMph: "2.2",
    avgGrade: "4.6", maxClimb: "+39.7", maxDescent: "-39.7",
    segGain: 2856, segLoss: 1821, netFt: "+1,014", netDir: "climb",
    elevS: 11161, elevE: 12175, conditions: "Afternoon, 55-62°F, ridgeline exposure — Mile and a Half of Sky",
    tailwind: 67, waterMl: 1088, dilutedMl: 994, plainMl: 94, tailwindConc: 0.0675,
    gels: 4, gelsPerHr: 2, carbTargetHr: 80, actualCarbHr: 80.0,
    saltCaps: 3, saltCapType: "original", sodiumHr: 733,
    caffeineHr: 0,
    cutoffClock: "8:00pm", cutoffHours: 14, modeledArrivalHours: 10.9, cutoffMarginHours: 3.1,
    amenities: {"water": true, "food": true, "dropBag": false, "crew": false},
    pickup: [],
    dropoff: [],
    socks: "No change", bladder: "Refill bladder fully — single mix for entire next segment",
    color: "#E8943A",
    note: "Exposed ridgeline section. Watch weather — afternoon is when storms are most likely to build.",
  },
  {
    id: 6, from: "Gold Hill", to: "Bridal Veil (Drop Bag #2)", miS: 26.5, miE: 35, dist: 8.5, distReal: 8.62,
    clockS: "Sat 4:54pm", clockE: "Sat 7:40pm", time: "2h46m", hours: 2.77, avgPace: "19:17", avgMph: "3.1",
    avgGrade: "-4.1", maxClimb: "+26.7", maxDescent: "-20.7",
    segGain: 2126, segLoss: 4464, netFt: "-1,856", netDir: "descent",
    elevS: 12175, elevE: 10319, conditions: "Late afternoon into evening, cooling 45-58°F, Black Bear + Brooklyn Pass",
    tailwind: 96, waterMl: 1439, dilutedMl: 1429, plainMl: 10, tailwindConc: 0.0675,
    gels: 6, gelsPerHr: 2, carbTargetHr: 80, actualCarbHr: 80.0,
    saltCaps: 4, saltCapType: "original", sodiumHr: 723,
    caffeineHr: 0,
    cutoffClock: "12:00am", cutoffHours: 18, modeledArrivalHours: 13.66, cutoffMarginHours: 4.34,
    amenities: {"water": true, "food": true, "dropBag": true, "crew": true, "note": "Hike required"},
    pickup: [
      "DROP BAG #2: full headlamp + battery swap", "Warm layer / gloves / hat",
      "2nd fresh socks", "Pole re-grip check", "Fresh base layer", "Anti-chafe reapply",
      "8-10 SIS gels resupply", "Tailwind resupply", "Pickles",
      "SaltStick capsules resupply", ],
    dropoff: ["DROP BAG #2 left here (picked up post-race)"],
    socks: "Change to fresh pair", bladder: "Refill bladder — last fill before overnight stretch",
    pacer: true,
    color: "#E8943A",
    note: "Most important stop of the race. Pacer joins here. Take 10-15 min. Sun sets ~8:15pm — headlamp goes on soon after this stop.",
  },
  {
    id: 7, from: "Bridal Veil (Drop Bag #2)", to: "Red Mtn", miS: 35, miE: 42, dist: 7, distReal: 7.08,
    clockS: "Sat 7:40pm", clockE: "Sat 10:26pm", time: "2h46m", hours: 2.76, avgPace: "23:23", avgMph: "2.6",
    avgGrade: "2.2", maxClimb: "+24.6", maxDescent: "-18.7",
    segGain: 3009, segLoss: 2244, netFt: "+820", netDir: "climb",
    elevS: 10319, elevE: 11139, conditions: "Dusk into dark, 40-50°F dropping, headlamp required by end of segment",
    tailwind: 123, waterMl: 1533, dilutedMl: 1533, plainMl: 0, tailwindConc: 0.08,
    gels: 3, gelsPerHr: 1, carbTargetHr: 65, actualCarbHr: 65.0,
    saltCaps: 3, saltCapType: "original", sodiumHr: 725,
    caffeineHr: 0,
    cutoffClock: "4:00am", cutoffHours: 22, modeledArrivalHours: 16.43, cutoffMarginHours: 5.57,
    amenities: {"water": true, "food": true, "dropBag": false, "crew": true, "note": "Vehicle access"},
    pickup: [],
    dropoff: [],
    socks: "No change", bladder: "Refill bladder fully — single mix for entire next segment",
    color: "#E8943A",
    note: "First fully dark segment. Pacer's job shifts to scanning trail with their own light. Crew access here (vehicle).",
  },
  {
    id: 8, from: "Red Mtn", to: "Burro Bridge", miS: 42, miE: 50, dist: 8, distReal: 8.31,
    clockS: "Sat 10:26pm", clockE: "Sun 1:09am", time: "2h43m", hours: 2.72, avgPace: "19:38", avgMph: "3.1",
    avgGrade: "-2.6", maxClimb: "+18.2", maxDescent: "-19.0",
    segGain: 1804, segLoss: 3068, netFt: "-1,134", netDir: "descent",
    elevS: 11139, elevE: 10005, conditions: "Full night, 35-42°F, net descent through Howard Fork drainage",
    tailwind: 105, waterMl: 1310, dilutedMl: 1310, plainMl: 0, tailwindConc: 0.08,
    gels: 3, gelsPerHr: 1, carbTargetHr: 60, actualCarbHr: 60.0,
    saltCaps: 4, saltCapType: "caffeine", sodiumHr: 728,
    caffeineHr: 45,
    cutoffClock: "7:00am", cutoffHours: 25, modeledArrivalHours: 19.14, cutoffMarginHours: 5.86,
    amenities: {"water": true, "food": true, "dropBag": false, "crew": true, "note": "Vehicle access"},
    pickup: [],
    dropoff: [],
    socks: "No change", bladder: "Refill bladder fully — single mix for entire next segment",
    color: "#E8943A",
    note: "Coldest stretch begins. Crew access here (vehicle) — good spot for a warm layer check with pacer.",
  },
  {
    id: 9, from: "Burro Bridge", to: "Ophir (Drop Bag #3)", miS: 50, miE: 56, dist: 6, distReal: 5.61,
    clockS: "Sun 1:09am", clockE: "Sun 3:15am", time: "2h07m", hours: 2.11, avgPace: "22:34", avgMph: "2.7",
    avgGrade: "1.7", maxClimb: "+16.1", maxDescent: "-19.4",
    segGain: 2063, segLoss: 1346, netFt: "+498", netDir: "climb",
    elevS: 10005, elevE: 10503, conditions: "Deep overnight, 33-40°F (coldest of race), Ophir Pass climb",
    tailwind: 39, waterMl: 843, dilutedMl: 584, plainMl: 259, tailwindConc: 0.0675,
    gels: 6, gelsPerHr: 3, carbTargetHr: 80, actualCarbHr: 80.0,
    saltCaps: 5, saltCapType: "caffeine", sodiumHr: 690,
    caffeineHr: 75,
    cutoffClock: "9:30am", cutoffHours: 27.5, modeledArrivalHours: 21.25, cutoffMarginHours: 6.25,
    amenities: {"water": true, "food": true, "dropBag": true, "crew": true, "note": "Hike required"},
    pickup: [
      "DROP BAG #3: fresh headlamp batteries (last chance)", "Dry socks (optional morale)",
      "Light gloves if not already carrying", "3-4 SIS gels resupply", "Tailwind resupply",
      "SaltStick capsules resupply", ],
    dropoff: ["DROP BAG #3 left here (picked up post-race)"],
    socks: "Optional 3rd change for morale", bladder: "Final refill of the race",
    color: "#E8943A",
    note: "Mile 56 is the classic DNF trap — 9 miles feels far at 3am after 21+ hours. Don't linger. Pacer keeps you moving.",
  },
  {
    id: 10, from: "Ophir (Drop Bag #3)", to: "Finish", miS: 56, miE: 65, dist: 9, distReal: 8.94,
    clockS: "Sun 3:15am", clockE: "Sun 6:00am", time: "2h45m", hours: 2.75, avgPace: "18:27", avgMph: "3.3",
    avgGrade: "-3.7", maxClimb: "+32.8", maxDescent: "-28.2",
    segGain: 2980, segLoss: 5109, netFt: "-1,740", netDir: "descent",
    elevS: 10503, elevE: 8763, conditions: "Pre-dawn into sunrise (~6:30am), 33-45°F warming, Oscar's Pass then final descent",
    tailwind: 104, waterMl: 1298, dilutedMl: 1298, plainMl: 0, tailwindConc: 0.08,
    gels: 5, gelsPerHr: 2, carbTargetHr: 75, actualCarbHr: 75.0,
    saltCaps: 3, saltCapType: "original", sodiumHr: 649,
    caffeineHr: 0,
    cutoffClock: "2:00pm", cutoffHours: 32, modeledArrivalHours: 24.0, cutoffMarginHours: 8.0,
    amenities: {"water": true, "food": true, "dropBag": false, "crew": false, "note": "Finish"},
    pickup: [],
    dropoff: [],
    socks: "No change", bladder: "Use remaining — no more refills",
    color: "#E8943A",
    note: "Final climb to Oscar's Pass (13,104ft, steepest climb on course at +24.8%) then descent to finish. Sunrise arrives as you descend Bear Creek.",
  },
];
