const baseSegments = [
  {
    id: 1, from: "Start", to: "Bridal Veil #1", miS: 0, miE: 4, dist: 4, distReal: 4.52,
    avgGrade: "6.5", maxClimb: "+11.3", maxDescent: "-0.6",
    segGain: 1982, segLoss: 0, netFt: "+1,556", netDir: "climb",
    elevS: 8763, elevE: 10319, conditions: "Cool morning, 45-55°F, climbing toward Wasatch area",
    cutoffClock: "7:30am", cutoffHours: 1.5,
    amenities: {"water": true, "food": false, "dropBag": false, "crew": false, "note": "Water only"},
    pickup: [],
    dropoff: [],
    socks: "Start fresh", bladder: "Fill bladder full before start — required every segment, not just long ones",
    color: "#E8943A",
    note: "Fresh legs, cool temps — settle into pace, don't go out too hot on the early climb.",
  },
  {
    id: 2, from: "Bridal Veil #1", to: "Tomboy", miS: 4, miE: 10, dist: 6, distReal: 6.17,
    avgGrade: "3.7", maxClimb: "+30.4", maxDescent: "-31.3",
    segGain: 3738, segLoss: 2493, netFt: "+1,193", netDir: "climb",
    elevS: 10319, elevE: 11512, conditions: "Warming, 50-60°F, sustained altitude 11-13.5K via Telluride Peak",
    cutoffClock: "11:00am", cutoffHours: 5,
    amenities: {"water": true, "food": true, "dropBag": false, "crew": false},
    pickup: [],
    dropoff: [],
    socks: "No change", bladder: "Refill bladder fully — single mix for entire next segment",
    color: "#E8943A",
    note: "Crosses Telluride Peak (13,500ft) — your highest point on course, first of three 13K+ crossings.",
  },
  {
    id: 3, from: "Tomboy", to: "Oak St (Drop Bag #1)", miS: 10, miE: 17, dist: 7, distReal: 6.47,
    avgGrade: "-8.1", maxClimb: "+37.0", maxDescent: "-37.1",
    segGain: 1362, segLoss: 4277, netFt: "-2,762", netDir: "descent",
    elevS: 11512, elevE: 8751, conditions: "Midday, 60-65°F (warmest of the day), steep Imogene descent",
    cutoffClock: "2:00pm", cutoffHours: 8,
    amenities: {"water": true, "food": true, "dropBag": true, "crew": true, "note": "Vehicle access"},
    pickup: [],
    dropoff: [],
    socks: "No change", bladder: "Refill bladder fully — single mix for entire next segment",
    color: "#E8943A",
    note: "Steepest descent on the course (-27.8%) happens in this segment. Quads will feel this.",
  },
  {
    id: 4, from: "Oak St (Drop Bag #1)", to: "Prospect", miS: 17, miE: 22, dist: 5, distReal: 5.06,
    avgGrade: "9.0", maxClimb: "+34.3", maxDescent: "-34.9",
    segGain: 3465, segLoss: 950, netFt: "+2,411", netDir: "climb",
    elevS: 8751, elevE: 11161, conditions: "Warmest part of day, 60-65°F, Ajax Peak climb begins",
    cutoffClock: "5:00pm", cutoffHours: 11,
    amenities: {"water": true, "food": true, "dropBag": false, "crew": false},
    pickup: ["DROP BAG #1: fresh socks", "Foot lube/blister kit", "Sunscreen reapply", "Spare pole tips", "6-8 SIS gels resupply", "Tailwind resupply", "LMNT resupply (primary for next 2 segments)", "Salt tabs (backup, just in case)"],
    dropoff: ["DROP BAG #1 left here (picked up post-race)"],
    socks: "Change to fresh pair", bladder: "Refill + check fit",
    color: "#E8943A",
    note: "Drop Bag #1. Quick stop — 5-8 min. Eat real food from aid station too if available.",
  },
  {
    id: 5, from: "Prospect", to: "Gold Hill", miS: 22, miE: 26.5, dist: 4.5, distReal: 4.21,
    avgGrade: "4.6", maxClimb: "+39.7", maxDescent: "-39.7",
    segGain: 2856, segLoss: 1821, netFt: "+1,014", netDir: "climb",
    elevS: 11161, elevE: 12175, conditions: "Afternoon, 55-62°F, ridgeline exposure — Mile and a Half of Sky",
    cutoffClock: "8:00pm", cutoffHours: 14,
    amenities: {"water": true, "food": true, "dropBag": false, "crew": false},
    pickup: [],
    dropoff: [],
    socks: "No change", bladder: "Refill bladder fully — single mix for entire next segment",
    color: "#E8943A",
    note: "Exposed ridgeline section. Watch weather — afternoon is when storms are most likely to build.",
  },
  {
    id: 6, from: "Gold Hill", to: "Bridal Veil #2 (Drop Bag #2)", miS: 26.5, miE: 35, dist: 8.5, distReal: 8.62,
    avgGrade: "-4.1", maxClimb: "+26.7", maxDescent: "-20.7",
    segGain: 2126, segLoss: 4464, netFt: "-1,856", netDir: "descent",
    elevS: 12175, elevE: 10319, conditions: "Late afternoon into evening, cooling 45-58°F, Black Bear + Brooklyn Pass",
    cutoffClock: "12:00am", cutoffHours: 18,
    amenities: {"water": true, "food": true, "dropBag": true, "crew": true, "note": "Hike required"},
    pickup: [
      "DROP BAG #2: full headlamp + battery swap", "Warm layer / gloves / hat",
      "2nd fresh socks", "Pole re-grip check", "Fresh base layer", "Anti-chafe reapply",
      "8-10 SIS gels resupply", "Tailwind resupply", "Pickles",
      "Salt tabs resupply (primary from here)", "LMNT (backup, just in case)",
    ],
    dropoff: ["DROP BAG #2 left here (picked up post-race)"],
    socks: "Change to fresh pair", bladder: "Refill bladder — last fill before overnight stretch",
    pacer: true,
    color: "#E8943A",
    note: "Most important stop of the race. Pacer joins here. Take 10-15 min. Sun sets ~8:15pm — headlamp goes on soon after this stop.",
  },
  {
    id: 7, from: "Bridal Veil #2 (Drop Bag #2)", to: "Red Mtn", miS: 35, miE: 42, dist: 7, distReal: 7.08,
    avgGrade: "2.2", maxClimb: "+24.6", maxDescent: "-18.7",
    segGain: 3009, segLoss: 2244, netFt: "+820", netDir: "climb",
    elevS: 10319, elevE: 11139, conditions: "Dusk into dark, 40-50°F dropping, headlamp required by end of segment",
    cutoffClock: "4:00am", cutoffHours: 22,
    amenities: {"water": true, "food": true, "dropBag": false, "crew": true, "note": "Vehicle access"},
    pickup: [],
    dropoff: [],
    socks: "No change", bladder: "Refill bladder fully — single mix for entire next segment",
    color: "#E8943A",
    note: "First fully dark segment. Pacer's job shifts to scanning trail with their own light. Crew access here (vehicle).",
  },
  {
    id: 8, from: "Red Mtn", to: "Burro Bridge", miS: 42, miE: 50, dist: 8, distReal: 8.31,
    avgGrade: "-2.6", maxClimb: "+18.2", maxDescent: "-19.0",
    segGain: 1804, segLoss: 3068, netFt: "-1,134", netDir: "descent",
    elevS: 11139, elevE: 10005, conditions: "Full night, 35-42°F, net descent through Howard Fork drainage",
    cutoffClock: "7:00am", cutoffHours: 25,
    amenities: {"water": true, "food": true, "dropBag": false, "crew": true, "note": "Vehicle access"},
    pickup: [],
    dropoff: [],
    socks: "No change", bladder: "Refill bladder fully — single mix for entire next segment",
    color: "#E8943A",
    note: "Coldest stretch begins. Crew access here (vehicle) — good spot for a warm layer check with pacer.",
  },
  {
    id: 9, from: "Burro Bridge", to: "Ophir (Drop Bag #3)", miS: 50, miE: 56, dist: 6, distReal: 5.61,
    avgGrade: "1.7", maxClimb: "+16.1", maxDescent: "-19.4",
    segGain: 2063, segLoss: 1346, netFt: "+498", netDir: "climb",
    elevS: 10005, elevE: 10503, conditions: "Deep overnight, 33-40°F (coldest of race), Ophir Pass climb",
    cutoffClock: "9:30am", cutoffHours: 27.5,
    amenities: {"water": true, "food": true, "dropBag": true, "crew": true, "note": "Hike required"},
    pickup: [
      "DROP BAG #3: fresh headlamp batteries (last chance)", "Dry socks (optional morale)",
      "Light gloves if not already carrying", "3-4 SIS gels resupply", "Tailwind resupply",
      "Salt tabs resupply", "LMNT (backup, just in case)",
    ],
    dropoff: ["DROP BAG #3 left here (picked up post-race)"],
    socks: "Optional 3rd change for morale", bladder: "Final refill of the race",
    color: "#E8943A",
    note: "Mile 56 is the classic DNF trap — 9 miles feels far at 3am after 21+ hours. Don't linger. Pacer keeps you moving.",
  },
  {
    id: 10, from: "Ophir (Drop Bag #3)", to: "Finish", miS: 56, miE: 65, dist: 9, distReal: 8.94,
    avgGrade: "-3.7", maxClimb: "+32.8", maxDescent: "-28.2",
    segGain: 2980, segLoss: 5109, netFt: "-1,740", netDir: "descent",
    elevS: 10503, elevE: 8763, conditions: "Pre-dawn into sunrise (~6:30am), 33-45°F warming, Oscar's Pass then final descent",
    cutoffClock: "2:00pm", cutoffHours: 32,
    amenities: {"water": true, "food": true, "dropBag": false, "crew": false, "note": "Finish"},
    pickup: [],
    dropoff: [],
    socks: "No change", bladder: "Use remaining — no more refills",
    color: "#E8943A",
    note: "Final climb to Oscar's Pass (13,104ft, steepest climb on course at +24.8%) then descent to finish. Sunrise arrives as you descend Bear Creek.",
  },
];
